@startuml
title FEUPBook

class Utilizador {
    id
    nome
    número de telemóvel
    género
}

class Multimédia {
    id
    título
}

class Publicação {
    id
    descrição
}

class Comentário {
    texto
}

class Mensagem {
    ' Pode ser string vazia '
    texto
}

class Conversa {
    nome
}

class Reação {
    tipo
}

class Evento {
    nome
}

' SQL já possui uma class de data, é necessário implementar outra? '
class Data {
    
}

class Página {
    nome
    website
}

class Localização {
    rua
    código postal
}

Utilizador "*" -- "*" Utilizador : amizade
(Utilizador, Utilizador) .. Data
Utilizador "*" -- "*" Utilizador : pedido de amizade
(Utilizador, Utilizador) .. Data
Utilizador "1" -- "*" Publicação : autor
Utilizador "*" -- "1" Localização : morada
Utilizador "*" -- "1" Data : data de nascimento

Publicação "1" *-- "*" Comentário
Publicação "1" o-- "*" Multimédia
Publicação "*" -right- "1" Data : data de publicação
Publicação "*" -- "1" Localização
Publicação "*" -- "*" Reação 

Página "1" -- "*" Publicação
Página "*" -- "*" Utilizador : seguidor
Página "*" -- "1" Utilizador : administrador
Página "*" -- "1" Data : data de criação

Conversa "1" *-- "*" Mensagem
Conversa "*" -- "1..*" Utilizador : participante
Conversa "*" -right- "*" Página : participante

Grupo "*" -down- "*" Utilizador : membro
Grupo "*" -down- "1" Utilizador : administrador
Grupo "1" -right- "*" Publicação
Grupo "*" -- "1" Data : data de criação

Multimédia <|-- Foto
Multimédia <|-- Vídeo
Multimédia <|-- Áudio
 
Mensagem "*" --- "1" Utilizador : autor
Mensagem "1" o-- "1" Multimédia : conteúdo
Mensagem "*" --- "1" Data : data de envio

Comentário "*" --- "1" Utilizador : autor
Comentário "*" -- "*" Reação

Reação "*" -- "1" Utilizador

Evento "*" --- "1" Data : data de realização
Evento "*" --- "*" Utilizador : participante
Evento "*" -right- "1" Localização : local a realizar-se

@enduml